name: Deploy Preprod
on:
  push:
    branches:
      - main

jobs:
  set_version:
    name: Set the version of the release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          echo version=$(cat version.md) >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.set_version.outputs.version }}

  gh-release:
    name: Create a release in GitHub
    needs:
      - set_version
    runs-on: ubuntu-latest
    if: test -z "${{ needs.set_version.outputs.version }}"
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: v${{ needs.set_version.outputs.version }}
          generate_release_notes: true